# Used cameras for the projection
cameras:
  - '/left'
  - '/right'
  - '/center'

# Topic setup
left:
  image_topic: image_raw
  camera_info_topic: camera_info
  extended_camera_info_topic: extended_camera_info_not_used
right:
  image_topic: image_raw
  camera_info_topic: camera_info
  extended_camera_info_topic: extended_camera_info_not_used
center:
  image_topic: image_raw
  camera_info_topic: camera_info
  extended_camera_info_topic: extended_camera_info_not_used
