# Used cameras for the projection
cameras:
  - '/m113/camera_front_left'
  - '/m113/camera_front'
  - '/m113/camera_front_right'

# Topic setup
/mm13:
    camera_front_left:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    camera_front:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    camera_front_right:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    
